FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    supervisor \
    && apt-get clean \
    && docker-php-ext-install pcntl

COPY docker/supervisord.conf /etc/supervisor/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord"]
